Table core.movies {
    id int [pk, note: 'a source table of movies']
    studio_id int
    title varchar(32)
    year int
}

Table core.studios {
    id int [pk]
    name varchar(32)
}

Ref {
    core.movies.studio_id > core.studios.id
}